# Generated by Django 4.0.5 on 2022-07-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_departments_company'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departments',
            unique_together={('dep_name', 'company')},
        ),
    ]
