# Generated by Django 4.0.5 on 2022-07-22 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_departments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('emp_name', 'department', 'company')},
        ),
    ]
